"""Remove links column from ParsedContent model

Revision ID: 6d73c232b803
Revises: None
Create Date: 2023-05-24 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6d73c232b803'
down_revision = None  # Set to None if this is the first migration
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('parsed_content', 'links')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parsed_content', sa.Column('links', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###
