"""Initial migration

Revision ID: 70b980592ede
Revises: 
Create Date: 2024-10-06 21:12:23.746160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70b980592ede'
down_revision = None
branch_labels = None
depends_on = None


import uuid
from sqlalchemy.orm import Session
from sqlalchemy.ext.declarative import declarative_base

Base = declarative_base()

class AllGroups(Base):
    __tablename__ = 'allgroups'
    uuid = sa.Column(sa.String(36), primary_key=True)
    authors = sa.Column(sa.Text)
    category = sa.Column(sa.Text)
    name = sa.Column(sa.Text)
    type = sa.Column(sa.Text)
    source = sa.Column(sa.Text)
    description = sa.Column(sa.Text)
    tlp = sa.Column(sa.Text)
    license = sa.Column(sa.Text)
    last_db_change = sa.Column(sa.Text)

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    tables = inspector.get_table_names()

    if 'allgroups' in tables:
        # If the table exists, we need to modify it
        with op.batch_alter_table('allgroups', schema=None) as batch_op:
            batch_op.alter_column('uuid',
                   existing_type=sa.NUMERIC(),
                   type_=sa.UUID(),
                   existing_nullable=False)
    else:
        # If the table doesn't exist, create it
        op.create_table('allgroups',
            sa.Column('uuid', sa.UUID(), nullable=False),
            sa.Column('authors', sa.Text(), nullable=True),
            sa.Column('category', sa.Text(), nullable=True),
            sa.Column('name', sa.Text(), nullable=True),
            sa.Column('type', sa.Text(), nullable=True),
            sa.Column('source', sa.Text(), nullable=True),
            sa.Column('description', sa.Text(), nullable=True),
            sa.Column('tlp', sa.Text(), nullable=True),
            sa.Column('license', sa.Text(), nullable=True),
            sa.Column('last_db_change', sa.Text(), nullable=True),
            sa.PrimaryKeyConstraint('uuid')
        )

    # Proceed with other table alterations

    if 'allgroups_values' not in tables:
        op.create_table('allgroups_values',
            sa.Column('uuid', sa.UUID(), nullable=False),
            sa.Column('actor', sa.Text(), nullable=True),
            sa.Column('country', sa.Text(), nullable=True),
            sa.Column('description', sa.Text(), nullable=True),
            sa.Column('information', sa.Text(), nullable=True),
            sa.Column('last_card_change', sa.Text(), nullable=True),
            sa.Column('motivation', sa.Text(), nullable=True),
            sa.Column('first_seen', sa.Text(), nullable=True),
            sa.Column('observed_sectors', sa.Text(), nullable=True),
            sa.Column('observed_countries', sa.Text(), nullable=True),
            sa.Column('tools', sa.Text(), nullable=True),
            sa.Column('operations', sa.Text(), nullable=True),
            sa.Column('sponsor', sa.Text(), nullable=True),
            sa.Column('counter_operations', sa.Text(), nullable=True),
            sa.Column('mitre_attack', sa.Text(), nullable=True),
            sa.Column('playbook', sa.Text(), nullable=True),
            sa.Column('allgroups_uuid', sa.UUID(), sa.ForeignKey('allgroups.uuid'), nullable=True),
            sa.PrimaryKeyConstraint('uuid')
        )


    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # ### end Alembic commands ###
