"""Add new fields to ParsedContent model

Revision ID: add_new_fields_to_parsed_content
Revises: 6d73c232b803
Create Date: 2023-05-24 11:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'add_new_fields_to_parsed_content'
down_revision = '6d73c232b803'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parsed_content', sa.Column('title', sa.String(length=255), nullable=True))
    op.add_column('parsed_content', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('parsed_content', sa.Column('pub_date', sa.String(length=100), nullable=True))
    op.add_column('parsed_content', sa.Column('creator', sa.String(length=255), nullable=True))
    op.add_column('parsed_content', sa.Column('categories', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('parsed_content', 'categories')
    op.drop_column('parsed_content', 'creator')
    op.drop_column('parsed_content', 'pub_date')
    op.drop_column('parsed_content', 'description')
    op.drop_column('parsed_content', 'title')
    # ### end Alembic commands ###
