services:
  weaviate:
    command:
      - --host
      - 0.0.0.0
      - --port
      - "6578"
      - --scheme
      - http
    image: cr.weaviate.io/semitechnologies/weaviate:1.26.5
    ports:
      - 6578:6578
      - 50051:50051
    volumes:
      - weaviate_data:/var/lib/weaviate
    restart: on-failure
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: "true"
      PERSISTENCE_DATA_PATH: "/var/lib/weaviate"
      DEFAULT_VECTORIZER_MODULE: "none"
      ENABLE_MODULES: ""
      CLUSTER_HOSTNAME: "node1"

  neo4j:
    image: neo4j:latest
    volumes:
      - ./neo4j/logs:/logs
      - ./neo4j/config:/config
      - ./neo4j/data:/data
      - ./neo4j/plugins:/plugins
    environment:
      - NEO4J_AUTH_FILE=/run/secrets/neo4j_auth_file
    ports:
      - "7474:7474"
      - "7687:7687"
    restart: always
    secrets:
      - neo4j_auth_file

  mongodb:
    image: mongo:6.0
    environment:
      - MONGO_INITDB_ROOT_USERNAME_FILE=/run/secrets/mongodb_auth
      - MONGO_INITDB_ROOT_PASSWORD_FILE=/run/secrets/mongodb_auth
    volumes:
      - ./mongodb_data:/data/db
    ports:
      - "27017:27017"
    restart: always
    secrets:
      - mongodb_auth

  sync_service:
    build:
      context: ./sync_service
      dockerfile: Dockerfile
    volumes:
      - ./sync_service:/app
    depends_on:
      - mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME_FILE=/run/secrets/mongodb_auth
      - MONGO_INITDB_ROOT_PASSWORD_FILE=/run/secrets/mongodb_auth
      - MONGO_DATABASE=${MONGO_DATABASE}
    restart: always
    secrets:
      - mongodb_auth

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11435:11435" # Expose Ollama's API
    command: ["pull", "llama3.2", "serve"] # Start the Ollama server to serve models
    volumes:
      - ./ollama_models:/root/.ollama/models # Persist models
    restart: always

volumes:
  weaviate_data:
  mongodb_data:
  ollama_models: # Persist Ollama models locally

secrets:
  neo4j_auth_file:
    file: ./neo4j_auth.txt
  mongodb_auth:
    file: ./mongodb_auth.txt
